import './globals.css'
import Nav from '@/components/Nav'
import { Poppins } from 'next/font/google'
import Footer from '@/components/Footer'

import 'vidstack/styles/base.css'
import 'vidstack/styles/ui/buttons.css'
import 'vidstack/styles/ui/captions.css'
import 'vidstack/styles/ui/tooltips.css'
import 'vidstack/styles/ui/live.css'
import 'vidstack/styles/ui/sliders.css'

import 'react-toastify/dist/ReactToastify.css'
import SupabaseProvider from "@/app/supabase-provider";


const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins'
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                            children,
                          }: {
  children: React.ReactNode
}) {
  return (
      <html suppressHydrationWarning={true} lang='en'>
      <body className={`${poppins.variable} font-poppins`}>
      <SupabaseProvider>
        <Nav />
        {children}
        <Footer />
      </SupabaseProvider>
      </body>
      </html>
  )
}
